# netlify.toml

[build]
  # O comando de build só precisa instalar as dependências
  command = "bun install" 

# Configuração do diretório de funções
[functions]
  directory = "netlify/edge-functions" 
  # O Netlify vai automaticamente buscar por TS/JS nesse diretório

# A SEÇÃO MAIS IMPORTANTE: CONFIGURAÇÃO DA ROTA DA EDGE FUNCTION
[[edge_functions]]
  # 'function' deve ser o nome do seu arquivo de entrada Edge Function 
  # (sem a extensão .ts ou .js), ou seja, 'index'.
  function = "index" 
  
  # 'path' deve cobrir as rotas que você deseja que o Elysia trate.
  # Para uma API completa, use "/*" para que *qualquer* requisição 
  # ao seu domínio passe pela sua função Elysia.
  path = "/*"